name: Renovate cronjob

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    uses: msdeleyto/gh-actions/.github/workflows/renovate.yaml@ec690eda1b005e885dd4b0f6f12c051746801ea5 # main
    secrets: inherit
