name: Renovate cronjob

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    uses: msdeleyto/gh-actions/.github/workflows/renovate.yaml@b926bdfe90e9d0792ee1d47358a038e38489e9ff # main
    secrets: inherit
